build-images:
	docker build -f imdb-service/Dockerfile imdb-service -t imdb-service
	docker build -f images-service/Dockerfile images-service -t images-service
	docker build -f storage-service/Dockerfile storage-service -t storage-service
	docker build -f find-the-actor-service/Dockerfile find-the-actor-service -t find-the-actor-service